name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy-testApp:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: pnpm 설치
      run: npm install -g pnpm

    - name: 종속성 설치
      run: pnpm install

    - name: build
      run: |
        unset CI  # 이 줄이 CI 변수를 제거합니다
        npm run build
      working-directory: projects/testApp

    - name: Deploy Project testApp to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects/testApp/build
          destination_dir: testApp
